version: '3.8'

services:
  db:
    image: postgres:14
    container_name: bookmarkit_db
    environment:
      POSTGRES_DB: bookmarkit
      POSTGRES_USER: bookmarkituser
      POSTGRES_PASSWORD: supersecret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bookmarkit_web
    command: ["sh", "entrypoint.sh"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      POSTGRES_DB: bookmarkit
      POSTGRES_USER: bookmarkituser
      POSTGRES_PASSWORD: supersecret
      POSTGRES_HOST: db

volumes:
  postgres_data:
