
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bookmarkit_web
    command: ["sh", "entrypoint.sh"]
    volumes:
      - .:/app
    ports:
      - "80:8000"
