version: '3.8'

services:
  db:
    image: postgres:14
    container_name: bookmarkit_db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bookmarkit_web
    command: ["sh", "entrypoint.sh"]
    volumes:
      - .:/app
    ports:
      - "80:8000"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data:
